version: '3.8'


services:
  web:
    image: web
    build:
      context: ./personal_blog_site
      dockerfile: Dockerfile.prod
    command: gunicorn  personal_blog_site.wsgi:application --bind 0.0.0.0:7001
    volumes:
      - static_volume:/home/personal_blog_site/web/staticfiles
      - media_volume:/home/personal_blog_site/web/media
    expose:
      - 7001
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - memcached
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
      - db_user
      - db_password
      - db_name
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
  memcached:
    image: memcached
    ports:
      - "11211:11211"
  nginx:
    image: nginx
    build: ./nginx
    volumes:
      - static_volume:/home/personal_blog_site/web/staticfiles
      - media_volume:/home/personal_blog_site/web/media
    ports:
      - "1337:80"
      - "3000:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:

secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt