# Generated by Django 4.1.5 on 2023-01-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='days_since_update',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
