# Generated by Django 4.1.5 on 2023-01-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=125, unique=True)),
                ('content', models.TextField()),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
